### PR TITLE
add doc to introduce Kubernetes as a service

### PR DESCRIPTION
**Pull request by kevinzs2048**

### CODE REVIEW

**Comment by kevinzs2048** [comment]
@kylekirkby ping for review. I make a mistake to close the PR before, sorry for that...

**Comment by kylekirkby** [comment]
> @kylekirkby ping for review. I make a mistake to close the PR before, sorry for that...

Hi @kevin-zhaoshuai,

Is this doc intended to be rendered as a page on the website?

**Comment by kevinzs2048** [comment]
Hi @kylekirkby not yet, just leave it at code repo would be enough.
I will need to add more info and prepare more details as a rendered info on the website.
Thanks!

**Comment by kevinzs2048** [comment]
@kylekirkby  Could you merge it? Need to publish this doc url when applying CNCF conformance test. Thanks

**Pull request merged**
